import { Inter } from "next/font/google";
import "./globals.css";

import QueryProvider from "@/providers/tanstackProvider";
import { Toaster } from "react-hot-toast";
import NavbarFooterWrapper from "@/components/navbar/navbarFooterWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tekra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <QueryProvider>
          <NavbarFooterWrapper>
            {children}
            <Toaster position="top-right" reverseOrder={false} />
          </NavbarFooterWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
