import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import QueryProvider from "@/providers/tanstackProvider";
import { Toaster } from "react-hot-toast";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tekra",
  description: "Generated by create next app",
  
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
       <QueryProvider>
        <main>
         <Navbar/>
        {children}
        <Toaster position="top-right" reverseOrder={false} />
        <Footer/>
       </main>
       </QueryProvider>
      </body>
    </html>
  );
}
